---
- name: sample book
  hosts: ansible_client
  remote_user: root
  become: yes
  tasks:
          - name: install httpd
            yum:
                    name: httpd
                    state: latest
          - name: run httpd
            service:
                    name: httpd
                    state: started
          - name: create content
            copy:
                content: "your test is served"
                dest: /var/www/html/index.html
